services:
  user-service:
    container_name: user-service
    image: user-service
    build: ./services/user
    ports:
      - "4001:4001"
    # volumes kalau dibuka waktu deploy, build compose up, muncul error dotenv module not found  
    # volumes:
    #   - ./services/user:/usr/local/app
    env_file:
      - ./services/user/.env
