services:
  user-service:
    container_name: user-service
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./services/user:/usr/local/app
    env_file:
      - ./services/user/.env
