services:
  user-service:
    container_name: user-service
    image: user-service
    build: ./services/user
    ports:
      - "8443:4001"
    # Sometimes, bind-mounted node_modules volumes (via volumes in docker-compose.yml) can conflict with the npm install step inside the container. 
    # To avoid this: Temporarily remove the volumes section
    # volumes:
    #   - ./services/user:/usr/local/app
    env_file:
      - ./services/user/.env
