version: '3.3'

services:
  user-service:
    container_name: user-service
    image: user-service
    build: ./services/user
    ports:
      - "4001:4001"
    volumes:
      - ./services/user:/usr/local/app

